Repository xirf/mathwithcode, pull requests merged in 2024-11, with the labels that each got.

#23 Restructure Content, Add New Topics, Change Matrix Multiplication Section, New Sponsors
  docs/.vitepress/sidebar.ts
  docs/.vitepress/sponsors.ts
  docs/algebra/graph.md
  docs/linear-algebra/matrix-multiplication.md
  docs/linear-algebra/matrix.md
  docs/linear-algebra/vector.md
  docs/public/img/sponsors/akiharu.jpg
  docs/public/img/vector.jpg
  docs/sponsors.md
Labels: enhancement

#21 Internationalization - English (en-US)
  docs/.vitepress/config.ts
  docs/.vitepress/contributors.ts
  docs/.vitepress/en.ts
  docs/.vitepress/id.ts
  docs/.vitepress/shared.config.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/Consent.vue
  docs/.vitepress/theme/components/ContributorsAside.vue
  docs/.vitepress/theme/components/HomePage.vue
  docs/en/algebra/function.md
  docs/en/algebra/graph.md
  docs/en/algebra/linear-equation.md
  docs/en/algebra/quadratic-equation.md
  docs/en/arithmetic/factors.md
  docs/en/arithmetic/numbers.md
  docs/en/arithmetic/operation-on-number.md
  docs/en/arithmetic/percent.md
  docs/en/guide/index.md
  docs/en/index.md
  docs/en/linear-algebra/linear-transformation.md
  docs/en/linear-algebra/matrix-multiplication.md
  docs/en/linear-algebra/vector.md
  docs/en/sponsors.md
  docs/en/statistics/measures-concentration-dispersion.md
  docs/id/algebra/function.md
  docs/id/algebra/graph.md
  docs/id/algebra/linear-equation.md
  docs/id/algebra/quadratic-equation.md
  docs/id/arithmetic/factors.md
  docs/id/arithmetic/numbers.md
  docs/id/arithmetic/operation-on-number.md
  docs/id/arithmetic/percent.md
  docs/id/guide/index.md
  docs/id/index.md
  docs/id/linear-algebra/linear-transformation.md
  docs/id/linear-algebra/matrix.md
  docs/id/linear-algebra/vector.md
  docs/id/sponsors.md
  docs/id/statistics/measures-concentration-dispersion.md
Labels: enhancement, I18N

#24 fixing inconsisten variable and ambigious description on percent
  docs/id/arithmetic/percent.md
Labels: bug

#27 style: rename variables to use snake_case convention
  docs/id/algebra/function.md
  docs/id/algebra/linear-equation.md
  docs/id/algebra/quadratic-equation.md
  docs/id/arithmetic/factors.md
  docs/id/arithmetic/numbers.md
  docs/id/arithmetic/operation-on-number.md
  docs/id/arithmetic/percent.md
  docs/id/linear-algebra/linear-transformation.md
  docs/id/linear-algebra/vector.md
  docs/id/statistics/measures-concentration-dispersion.md
Labels: enhancement, good first issue
